all : lab.c
	make -C /lib/modules/5.3.0-29-generic/build M=/home/rayli/LinuxKernel/Exercises/Chapter3 modules
clean :
	make -C /lib/modules/5.3.0-29-generic/build M=/home/rayli/LinuxKernel/Exercises/Chapter3 clean 
obj-m := lab.o 
