#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
echo "A customer entry by Ray"
menuentry "Custom Linux Boot Entry" {
set root=(hd0,1)
linux /boot/vmlinuz initcall_debug init=/bin/bash rdinit=/bin/sh
initrd /boot/initrd.img
}
EOF
